### ISSUE TITLE
AWS CloudHSM support?

### ISSUE THREAD

**Issue by tluyben** [Pkcs11Interop/Pkcs11Interop#127]
Does it work or did anyone use this with CloudHSM; my client is migrating from their own Luna to AWS.

**Comment by jariq** [comment]
Take a look at [our mailinglist](https://groups.google.com/d/forum/pkcs11interop). Several users reported there that they are using Pkcs11Interop with [CloudHSM](https://groups.google.com/forum/#!searchin/pkcs11interop/CloudHSM%7Csort:date).

**Comment by raedabusanad** [comment]
Can anyone of the users post a sample code?
 I get this error 
Net.Pkcs11Interop.Common.Pkcs11Exception
  HResult=0x80131500
  Message=Method C_Initialize returned CKR_GENERAL_ERROR
  Source=Pkcs11Interop
  StackTrace:
   at Net.Pkcs11Interop.HighLevelAPI41.Pkcs11Library.Initialize(AppType appType)
   at Net.Pkcs11Interop.HighLevelAPI41.Pkcs11Library..ctor(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at Net.Pkcs11Interop.HighLevelAPI41.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at Net.Pkcs11Interop.HighLevelAPI.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at Program.<Main>$(String[] args) in C:\Users\raed.abusanad\source\trusted-signing-server\TrustedSigningServer\Hsm.ConsoleApp\Program.cs:line 9

  This exception was originally thrown at this call stack:
    [External Code]
    Program.<Main>$(string[]) in Program.cs



`
using Net.Pkcs11Interop.Common;
using Net.Pkcs11Interop.HighLevelAPI;

string pkcs11LibraryPath = @"cloudhsm_pkcs11.dll";

var factories = new Pkcs11InteropFactories();

using (var pkcs11Library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, pkcs11LibraryPath, AppType.MultiThreaded))
{
    ILibraryInfo libraryInfo = pkcs11Library.GetInfo();

    Console.WriteLine("Library");
    Console.WriteLine("  Manufacturer:       " + libraryInfo.ManufacturerId);
    Console.WriteLine("  Description:        " + libraryInfo.LibraryDescription);
    Console.WriteLine("  Version:            " + libraryInfo.LibraryVersion);
}

Console.WriteLine("Press any key to exit");
Console.ReadLine();
`
