### ISSUE TITLE
MacCatalyst - Pkcs11Interop is not supported on this platform

### ISSUE THREAD

**Issue by angelru** [Pkcs11Interop/Pkcs11Interop#215]
I am using NET MAUI in with mac catalyst and I get this exception

```
   at Net.Pkcs11Interop.Common.Platform.DetectPlatform()
   at Net.Pkcs11Interop.Common.Platform.get_IsLinux()
   at Net.Pkcs11Interop.Common.Platform.get_NativeULongSize()
   at Net.Pkcs11Interop.HighLevelAPI.Factories.Pkcs11LibraryFactory..ctor()
   at Net.Pkcs11Interop.HighLevelAPI.Pkcs11InteropFactories..ctor()
```

**Comment by jariq** [comment]
Nope. I am not currently working on anything maccatalyst related.

**Comment by angelru** [comment]
@jariq 

I don't know why your library doesn't detect an application that runs with Mac Catalyst, I downloaded the project and returned 
`_isMacOsX = true ` 

but it returns an exception:
`{System.DllNotFoundException: libdl at Net.Pkcs11Interop.Common.UnmanagedLibrary.Load(String fileName) in /Users/development/Desktop/src/Pkcs11Interop/Common/UnmanagedLibrary.cs:line 74 at Net.Pkcs11Interop.LowLevelAPI80.Pkcs.11 ctor`

**Comment by jariq** [comment]
@angelru it's really hard for me to understand what your problem is and help you because you're describing it in a multiple comments in a quite chaotic way. Please be as detailed as you can be and provide:

* the version of Pkcs11Interop you are using
* the version of .NET you are using
* the version of operating system you are using
* the description of the actual result (what is actually happening) and the expected result (what would you expect to happen instead)
* the exception you are getting along with a **full** stack trace
* snippet of the problematic code

**Comment by jariq** [comment]
Information you provided:

* the version of Pkcs11Interop you are using: 5.1.2
* the version of .NET you are using: .NET 7
* the description of the actual result (what is actually happening) and the expected result (what would you expect to happen instead): Gets exception while calling `factories = new Pkcs11InteropFactories();` 
* snippet of the problematic code:  `factories = new Pkcs11InteropFactories();` 

Information you still need to provide:

* the version of operating system you are using
* the exception you are getting along with a **full** stack trace

**Comment by angelru** [comment]
` NET 7 MAUI`

`macOS Monterey 12.6.1`

`Pkcs11Interop is not supported on this platform`

```
   at Net.Pkcs11Interop.Common.Platform.DetectPlatform() in /Users/desarrollo/Desktop/src/Pkcs11Interop/Common/Platform.cs:line 217
   at Net.Pkcs11Interop.Common.Platform.get_IsLinux() in /Users/desarrollo/Desktop/src/Pkcs11Interop/Common/Platform.cs:line 88
   at Net.Pkcs11Interop.Common.Platform.get_NativeULongSize() in /Users/desarrollo/Desktop/src/Pkcs11Interop/Common/Platform.cs:line 127
   at Net.Pkcs11Interop.HighLevelAPI.Factories.Pkcs11LibraryFactory..ctor() in /Users/desarrollo/Desktop/src/Pkcs11Interop/HighLevelAPI/Factories/Pkcs11LibraryFactory.cs:line 43
   at Net.Pkcs11Interop.HighLevelAPI.Pkcs11InteropFactories..ctor() in /Users/desarrollo/Desktop/src/Pkcs11Interop/HighLevelAPI/Pkcs11InteropFactories.cs:line 150
```

**Comment by jariq** [comment]
OK so let's sum it up once again:

* the version of Pkcs11Interop you are using:  
  > Pkcs11Interop 5.1.2
* the version of .NET you are using:
  > .NET 7 MAUI with maccatalyst
* the version of operating system you are using:
  > macOS Monterey 12.6.1
* the description of the actual result (what is actually happening) and the expected result (what would you expect to happen instead):
  > Gets exception while calling `factories = new Pkcs11InteropFactories();`
* snippet of the problematic code:
  > `factories = new Pkcs11InteropFactories();`
* the exception you are getting:  
  > `Net.Pkcs11Interop.Common.UnsupportedPlatformException` thrown at https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.2/src/Pkcs11Interop/Common/Platform.cs#L217

**Comment by jariq** [comment]
Could you please add following code to your application and let me know what it prints to STDOUT?

```csharp
Console.WriteLine($"Is Windows: {System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.Windows)}");
Console.WriteLine($"Is Windows: {System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.Linux)}");
Console.WriteLine($"Is Windows: {System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.OSX)}");
```

**Comment by angelru** [comment]
> ```cs
> Console.WriteLine($"Is Windows: {System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.Windows)}");
> Console.WriteLine($"Is Windows: {System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.Linux)}");
> Console.WriteLine($"Is Windows: {System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.OSX)}");
> ```

2022-11-24 20:18:59.281 RADesktop[693:6870] Is Windows: False
2022-11-24 20:18:59.281 RADesktop[693:6870] Is Windows: False
2022-11-24 20:18:59.281 RADesktop[693:6870] Is Windows: False

**Comment by jariq** [comment]
Welp, `System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.OSX)` returning `false` in .NET 7 MAUI app running on macOS 12.6.1 is an issue that should be fixed in https://github.com/dotnet/runtime/.

**Comment by angelru** [comment]
I understand it's a NET problem, but one thing, I unload your project and return `_isMacOsX = true` where the exception is thrown.

and then it tells me this:
`{System.DllNotFoundException: libdl at Net.Pkcs11Interop.Common.UnmanagedLibrary.Load(String fileName) in /Users/development/Desktop/src/Pkcs11Interop/Common/UnmanagedLibrary.cs:line 74 at Net.Pkcs11Interop.LowLevelAPI80.Pkcs.11 ctor`

**Comment by Thordax** [comment]
> @jariq
> 
> I don't know why your library doesn't detect an application that runs with MacCatalyst, I downloaded the project and returned `_isMacOsX = true `
> 
> but it returns an exception: `{System.DllNotFoundException: libdl at Net.Pkcs11Interop.Common.UnmanagedLibrary.Load(String fileName) in /Users/development/Desktop/src/Pkcs11Interop/Common/UnmanagedLibrary.cs:line 74 at Net.Pkcs11Interop.LowLevelAPI80.Pkcs.11 ctor`
> 
> and load library: `"/usr/local/lib/libeTPkcs11.dylib"`
> 
> I think I remember it used to work.
> 
> ```
> 
> MMP : warning MM2006: Native library 'libdl' was referenced but could not be found.
> MMP : warning MM2009: Referenced by Net.Pkcs11Interop.Common.NativeMethods.dlopen
> MMP : warning MM2009: Referenced by Net.Pkcs11Interop.Common.NativeMethods.dlerror
> MMP : warning MM2009: Referenced by Net.Pkcs11Interop.Common.NativeMethods.dlclose
> MMP : warning MM2009: Referenced by Net.Pkcs11Interop.Common.NativeMethods.dlerror
> MMP : warning MM2009: Referenced by Net.Pkcs11Interop.Common.NativeMethods.dlsym
> MMP : warning MM2009: Referenced by Net.Pkcs11Interop.Common.NativeMethods.dlerror
> ```
> 
> how can i add https://learn.microsoft.com/en-us/dotnet/api/system.operatingsystem.ismaccatalyst?view=net-7.0

Hi, I encounter the same issue. By running step by step debug, I also have an exception stating that libdl is missing :

NativeMethods.cs this method :
```
/// <summary>
/// Loads the dynamic library
/// </summary>
/// <param name='filename'>Library filename.</param>
/// <param name='flag'>RTLD_LAZY for lazy function call binding or RTLD_NOW immediate function call binding.</param>
/// <returns>Handle for the dynamic library if successful, IntPtr.Zero otherwise.</returns>
[DllImport("libdl", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
internal static extern IntPtr dlopen(string filename, int flag);
```

Exception :

`DllNotFoundException : libdl`

StackTrace :

> 
>   at Net.Pkcs11Interop.Common.UnmanagedLibrary.Load(String fileName) in /Users/yr/Projects/turbosignv3/Pkcs11Interop-master/src/Pkcs11Interop/Common/UnmanagedLibrary.cs:line 74
>    at Net.Pkcs11Interop.LowLevelAPI80.Pkcs11Library..ctor(String libraryPath) in /Users/yr/Projects/turbosignv3/Pkcs11Interop-master/src/Pkcs11Interop/LowLevelAPI80/Pkcs11Library.cs:line 66
>    at Net.Pkcs11Interop.HighLevelAPI80.Pkcs11Library..ctor(Pkcs11InteropFactories factories, String libraryPath, AppType appType) in /Users/yr/Projects/turbosignv3/Pkcs11Interop-master/src/Pkcs11Interop/HighLevelAPI80/Pkcs11Library.cs:line 120
>    at Net.Pkcs11Interop.HighLevelAPI80.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType) in /Users/yr/Projects/turbosignv3/Pkcs11Interop-master/src/Pkcs11Interop/HighLevelAPI80/Factories/Pkcs11LibraryFactory.cs:line 44
>    at Net.Pkcs11Interop.HighLevelAPI.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType) in /Users/yr/Projects/turbosignv3/Pkcs11Interop-master/src/Pkcs11Interop/HighLevelAPI/Factories/Pkcs11LibraryFactory.cs:line 68
>    at turbosignv3.MainPage.TestPkcs11() in /Users/yr/Projects/turbosignv3/turbosignv3/MainPage.xaml.cs:line 50
>

**Comment by jariq** [comment]
Could any of you please share with me a minimal MAUI app that replicates the problem? So I can easily run [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Thordax** [comment]
Is this project Ok for you ? You just have to click the first button after launching the project 

https://we.tl/t-7UGrF2CS4c

**Comment by angelru** [comment]
@Thordax  @jariq 

Something must have changed in .NET MAUI & MacCatalyst or macOS in some update, a few months ago it worked fine.

**Comment by jariq** [comment]
@Thordax the project you provided does not build on my mac. I had to disable Android and iOS platforms in `turbosingv3` project in order to get rid of some errors but now with only maccatalyst left it still does not build with the following error:

```
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.4.2372/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture x86_64:
    "_C_CancelFunction", referenced from:
          -u command line option
    "_C_CloseAllSessions", referenced from:
          -u command line option
```

I'd say it's missing empty-pkcs11 library during the linking phase. Any hint how to fix this?

**Comment by angelru** [comment]
Will it be solved by changing the linker?

**Comment by angelru** [comment]
> @Thordax the project you provided does not build on my mac. I had to disable Android and iOS platforms in `turbosingv3` project in order to get rid of some errors but now with only maccatalyst left it still does not build with the following error:
> 
> ```
> /usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.4.2372/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
> Undefined symbols for architecture x86_64:
>     "_C_CancelFunction", referenced from:
>           -u command line option
>     "_C_CloseAllSessions", referenced from:
>           -u command line option
> ```
> 
> I'd say it's missing empty-pkcs11 library during the linking phase. Any hint how to fix this?

```
<ItemGroup>
		<NativeReference Include="Libs/libempty-pkcs11-catalyst.dylib">
			<Kind>Dynamic</Kind>
			<SmartLink>False</SmartLink>
		</NativeReference>
	</ItemGroup>
```

**Comment by Thordax** [comment]
Hi @angelru I tried to add that reference in the csproj file, but I suppose the file "libempty-pkcs11-catalyst.dylib" is missing. 

How could I get that file ? Should I compile it somehow ?

**Comment by angelru** [comment]
> Hi @angelru I tried to add that reference in the csproj file, but I suppose the file "libempty-pkcs11-catalyst.dylib" is missing.
> 
> How could I get that file ? Should I compile it somehow ?

https://github.com/Pkcs11Interop/empty-pkcs11/pull/3/files

**Comment by Thordax** [comment]
Thanks @angelru I got the same error unfortunately (missing file "libdl", and I don't know how to get it).

Without it, I can't call the native method "dlopen" in the NativeMethod.cs file :

```
[DllImport("libdl", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
internal static extern IntPtr dlopen(string filename, int flag);
```

**Comment by angelru** [comment]
> Thanks @angelru I got the same error unfortunately (missing file "libdl", and I don't know how to get it).
> 
> Without it, I can't call the native method "dlopen" in the NativeMethod.cs file :
> 
> ```
> [DllImport("libdl", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
> internal static extern IntPtr dlopen(string filename, int flag);
> ```

yes, same issue...

**Comment by angelru** [comment]
@jariq @Thordax 
something new?

**Comment by angelru** [comment]
is there news?

**Comment by jariq** [comment]
Nope. I am not currently working on anything MAUI or maccatalyst related.

**Comment by jariq** [comment]
I'm gonna take a look at this in #253. My free time is currently limited so I have no idea when it will be finished.

**Comment by Murhaf-Mo** [comment]
Hi,

This issue is caused by a limitation in the .NET runtime rather than a problem with Pkcs11Interop itself. Specifically, on Mac Catalyst, the method RuntimeInformation.IsOSPlatform(OSPlatform.OSX) incorrectly returns false, which prevents Pkcs11Interop from recognizing the platform as macOS. This limitation affects the ability to detect and adapt to the environment correctly.

Root Cause
The .NET runtime does not detect Mac Catalyst as OSPlatform.OSX. Instead, it treats Mac Catalyst as an unrecognized platform, leaving libraries like Pkcs11Interop unable to determine the correct runtime environment. This behavior has been documented in the .NET runtime repository ([dotnet/runtime#104160](https://github.com/dotnet/runtime/issues/104160)).

Workaround for .NET Standard 2.0
Since RuntimeInformation.IsOSPlatform(OSPlatform.OSX) does not return true on Mac Catalyst, you can modify the DetectPlatform method to assume Mac Catalyst is macOS. Here's an example workaround that treats any unknown platform as _isMacOsX:
```c#
private static void DetectPlatform()
{
    if (_isWindows || _isLinux || _isMacOsX)
        return;

#if NETSTANDARD2_0
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        _isWindows = true;
    }
    else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
    {
        // Note: Android gets here too
        _isLinux = true;
    }
    else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
    {
        // Treat all Apple platforms (including Mac Catalyst) as macOS
        _isMacOsX = true;
    }
    else
    {
        // Fallback assumption: Assume macOS for unrecognized platforms
        _isMacOsX = true;

        // Console.WriteLine("Unknown platform detected, assuming macOS");
    }
#else
    // Platform detection for other frameworks
#endif
}``` 

We need to find another way to detect Mac Catalyst until the issue is resolved in the dot net run time. This work around is working on my M2 Mac. I am not sure why returning ` _isMacOsX = true; ` didn't work for you @angelru @Thordax  did you change it in the same place as I did?

**Comment by jariq** [comment]
I've created new branch called [`253-support-for-maccatalyst`](https://github.com/Pkcs11Interop/Pkcs11Interop/tree/253-support-for-maccatalyst) and added simple MacCatalyst MAUI app into `other/Pkcs11Interop.Maui` directory.

In order to get it running I had to:
- **Build latest development version of [`empty-pkcs11`](https://github.com/Pkcs11Interop/empty-pkcs11) for Apple silicon CPUs**  
  It is needed to successfully build MAUI app that references Pkcs11Interop.
- **Build latest development version of [`pkcs11-mock`](https://github.com/Pkcs11Interop/pkcs11-mock) for Apple silicon CPUs**  
  This is dummy PKCS#11 library that is great for testing purposes. However in a real world scenario it would be replaced by PKCS#11 library from some card/HSM vendor.
- **Modify Pkcs11Interop to allow manual override of automatic platform detection**  
  See https://github.com/Pkcs11Interop/Pkcs11Interop/commit/cb65f3be0d668ea9e10c767891e00ba9136b38c2 for more details.
- **Modify MacCatalyst MAUI app `.csproj` file to get it building**  
  See https://github.com/Pkcs11Interop/Pkcs11Interop/commit/5e11e327b4a7424df7b56499496386dab043a102#diff-47c177fbb1e1f1bb08d6fd4c1e5a4e6c8eeff665335b95401b1d20fb068b0303 for more details.

Now I can rebuild and run the app by executing `other/Pkcs11Interop.Maui/rebuild-and-run.sh` script.

I added following code into the app:

```csharp
Net.Pkcs11Interop.Common.Platform.IsMacOsX = true;
var libraryPath = "./pkcs11-mock/macos/pkcs11-mock.dylib";
var factories = new Pkcs11InteropFactories();
var library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, libraryPath, AppType.MultiThreaded);
var info = library.GetInfo();
```

The app works fine with .NET 8 on my borrowed M1 based macOS 14.5. I am currently updating to macOS 15.2 and will test again.

I did not get any `libdl` or `dlopen` related errors described by @angelru and @Thordax.

Can you please test whether these changes work for you so I could merge them into master?

**Comment by Murhaf-Mo** [comment]
Its also working on a vender specific pkcs11 lib, my macOS version is Version 15.1 (24B83) 

<img width="525" alt="Image" src="https://github.com/user-attachments/assets/3d850331-a164-430a-8384-7a11f84e6066" />

**Comment by jariq** [comment]
The upcoming release of Pkcs11Interop 5.3.0 can be used in MacCatalyst MAUI apps so I am closing this issue now.

Details are described in https://github.com/Pkcs11Interop/Pkcs11Interop/issues/253#issuecomment-2629334237.

Please let me know if you manage to successfully publish MacCatalyst MAUI app that uses Pkcs11Interop 😉

**Comment by angelru** [comment]
Many thanks!
