### ISSUE TITLE
[Issue] PKCS11Interop.dll version 1.3.0 getting issue "The specified module could not be found"

### ISSUE THREAD

**Issue by kogoel** [Pkcs11Interop/Pkcs11Interop#237]
Steps and Error Details:
While running samples with the PKCS11Interop.dll version 1.3.0 with internal library, getting below error:
The specified module could not be found
   at Net.Pkcs11Interop.LowLevelAPI.UnmanagedLibrary.Load(String fileName)
   at Net.Pkcs11Interop.LowLevelAPI.Pkcs11..ctor(String libraryPath)
   at Net.Pkcs11Interop.HighLevelAPI.Pkcs11..ctor(String libraryPath, Boolean useOsLocking)

Sample running on Windows 2016 server, while same code is working as expected in windows server 2022.

**Comment by jariq** [comment]
Pkcs11Interop 1.3.0 is almost 10 years old and is no longer supported. Please update Pkcs11Interop to the latest release first and if the problem persists then please open new issue.
